// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

package main

import "fmt"

func main() {
	var pair [2]int
	pair[0] = 1
	pair[1] = 1
	sum := 0
	for (pair[0] + pair[1]) < 4000000 {
		newItem := pair[0] + pair[1]
		pair[0] = pair[1]
		pair[1] = newItem
		if pair[1]%2 == 0 {
			sum += pair[1]
		}
	}

	fmt.Printf("total= %d\n", sum)
}
